dist: bionic
language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.7"
      env: TOXENV=linters

install:
  - pip install tox tox-venv tox-travis

script:
  - tox

after_success:
  - pip install codecov
  - codecov -e TOXENV

notifications:
  email: false
